import Head from "next/head";
import Slider from "../components/Slider";
import Hero from "../components/Hero";
import Directors from "../components/Directors";
import Teams from "../components/Teams";
import Testimonials from "../components/Testimonials";
import NewsTicker from "../components/NewsTicker";
import Stats from "../components/Stats";
import BlogBanner from "../components/BlogBanner";
import LatestBLog from "../components/LatestBLog";

export default function Home() {
  return (
    <div>
      <Head>
        <title>DIMA Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_small.ico" />
      </Head>

      <main className="p-4 space-y-2">
        <NewsTicker />
        <Slider />
        <Hero />
        <Directors />
        <Teams />
        <BlogBanner />
        <Testimonials />
        <Stats />
        <LatestBLog />
      </main>
    </div>
  );
}
